### PR TITLE
fix(security): cap Discord download sizes

### LINKED ISSUE #377: security: cap Discord attachment and embed downloads to prevent DoS
## Summary

Discord message ingestion currently downloads attachments and embed images without request timeouts or streamed byte caps. This lets a Discord participant trigger unbounded server-side reads during message processing.

## Severity

- Rating: P1 / High
- Class: Denial of service / resource exhaustion

## Affected code

- `src/channels/discord.ts:998` fetches image attachments with `fetch(a.url)`
- `src/channels/discord.ts:1007` buffers the full body with `await resp.arrayBuffer()`
- `src/channels/discord.ts:1054` fetches text attachments with `fetch(a.url)`
- `src/channels/discord.ts:1055` buffers the full text with `await resp.text()`
- `src/channels/discord.ts:1089` fetches embed images with `fetch(imageUrl)`
- `src/channels/discord.ts:1097` buffers the full body with `await resp.arrayBuffer()`

## Why this is a security issue

- No Discord download path applies `AbortSignal.timeout(...)` or another transfer timeout.
- Image and embed paths read the entire response into memory before writing to disk.
- Text attachment handling trusts Discord's reported `a.size`, but does not verify the number of bytes actually received.
- The embed-image path can fetch arbitrary remote URLs present in embeds, not only Discord CDN objects.

As a result, an attacker who can post in a connected Discord channel can cause OmniClaw to:

- hold a worker on a very slow or never-ending response,
- allocate memory proportional to the response body,
- write oversized payloads into the group media directory.

## Reproduction

1. Connect OmniClaw to a Discord channel.
2. Send one of the following messages in that channel:
   - a large image attachment near Discord's upload limit, or
   - a bot/webhook message with `embed.image.url` pointing at a very large or very slow remote response.
3. Observe OmniClaw's Discord adapter processing the message.
4. The server will fetch the resource immediately and buffer the full body via `arrayBuffer()` or `text()` with no timeout or byte cap.
5. Repeating this with several messages can spike memory, fill disk, or stall ingestion for the affected group.

## Suggested remediation

- Add explicit timeouts to all Discord-side fetches.
- Replace `arrayBuffer()` / `text()` buffering with streaming reads that abort after a strict byte cap.
- Enforce actual bytes-read limits even when metadata such as `a.size` is present.
- Consider centralizing capped-download logic so Discord attachment, embed, and web image fetches share the same guardrails.

## Duplicate check

- Reviewed issue `#254` and merged PR `#353`; they address Discord image/embed support, not timeout or byte-cap enforcement.
- Searched open and closed issues/PRs for Discord attachment download timeout/size security work and found no duplicate tracking issue.

### PR DESCRIPTION
**Pull request by Peyton-Spencer**
## Summary
- add a streamed Discord download helper that applies a 15s timeout and hard byte caps before buffering attachment or embed bodies
- reuse the helper for image, embed, and text attachment ingestion so oversized or never-ending responses fail closed instead of exhausting memory
- add regression coverage for the byte-limit guard and the download wrappers used by the Discord adapter

## Testing
- `bun test src/channels/discord.test.ts`
- `bun run typecheck`

Fixes #377.

## Summary by CodeRabbit

* **New Features**
  * Discord attachments now have enforced download size limits (images up to 10MB, text up to 100KB) and built-in timeout protection to prevent large or stalled downloads.

* **Tests**
  * Added tests covering attachment download guards, stream size enforcement, timeout behavior, and related error handling.

### CODE REVIEW

File: src/channels/discord.ts [hunk 1]
```diff
@@ -63,6 +63,80 @@ const IMAGE_EXTENSIONS = new Set([
...
+const DISCORD_DOWNLOAD_TIMEOUT_MS = 15_000;
+const MAX_DISCORD_BINARY_DOWNLOAD_BYTES = 10 * 1024 * 1024;
+const MAX_DISCORD_TEXT_DOWNLOAD_BYTES = 100 * 1024;
+
+export async function readStreamWithByteLimit(
+  stream: ReadableStream<Uint8Array> | null,
+  maxBytes: number,
+): Promise<Buffer> {
+  if (!stream) return Buffer.alloc(0);
+
```
Comment (Peyton-Spencer) [inline src/channels/discord.ts]: Non-blocking: This `null` stream early return is a reasonable defensive check, but it has no test coverage. A quick `readStreamWithByteLimit(null, 100)` assertion would lock it in.

**Review by Peyton-Spencer — COMMENTED** [review]
Reviewed: streaming byte-limit approach is solid, tests cover the critical paths. Merging.
