### PR TITLE
fix(web): cap login request bodies

### LINKED ISSUE #548: security: cap Web UI login request bodies
## Summary

The session-auth login handler accepts unbounded form bodies. In `src/web/server.ts`, `POST /login` calls `req.formData()` directly, while the other authenticated write endpoints already use `readJsonBody(..., MAX_WEB_JSON_BODY_BYTES)` and reject oversized payloads with `413 Request body too large`.

This leaves `/login` as an easy memory/CPU denial-of-service target on deployments that expose the Web UI and enable `WEB_PASSWORD`.

## Severity

P2

## Affected code

- `src/web/server.ts:240-256`
- `src/request-body.ts:16-70`
- `src/web/routes.ts:439-454`
- `src/web/routes.ts:552-571`
- `src/web/routes.ts:873-888`
- `src/web/routes.ts:1030-1049`
- `src/web/routes.ts:1114-1138`

## Why this is a vulnerability

- `req.formData()` parses the full request body before password verification.
- `/login` is intentionally reachable before authentication, so any network client that can reach the Web UI can hit it.
- The codebase already treats oversized request bodies as a security concern elsewhere: webhook intake, trusted-peer auth, discovery routes, and authenticated Web UI JSON mutations all enforce explicit byte caps.
- Leaving the auth endpoint uncapped gives an attacker a simpler pre-auth exhaustion path than the already-hardened routes.

## Reproduction

1. Start OmniClaw with the Web UI exposed and session auth enabled via `WEB_PASSWORD`.
2. Send a very large request body to `/login`, for example a large `multipart/form-data` upload or a huge urlencoded `password=` value.
3. Observe that the server attempts to parse the full form payload instead of rejecting it early with `413`.
4. Repeat a few times concurrently to amplify memory pressure and CPU spent parsing bodies.

Example shape:

```bash
perl -e 'print "password=" . ("A" x (50*1024*1024))' | \
  curl -i \
    -X POST \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    --data-binary @- \
    http://127.0.0.1:3000/login
```

## Expected behavior

The login route should apply the same bounded-body pattern as the other Web UI write routes and fail oversized bodies with `413 Request body too large` before form parsing.

## Suggested fix

- Add a dedicated max body size for login form submissions, likely matching the existing 1 MiB Web UI JSON cap.
- Parse the raw body through the shared bounded reader before constructing `URLSearchParams` or otherwise extracting the password field.
- Add regression tests covering both over-limit `Content-Length` and streaming bodies that exceed the limit mid-read.

### PR DESCRIPTION
**Pull request by Peyton-Spencer**
## Summary
- cap Web UI login request bodies before form parsing so `POST /login` cannot buffer arbitrary-size pre-auth form payloads
- reuse the shared bounded request-body path for form parsing and return `413` on oversized login requests
- add helper and auth regressions for both oversized `Content-Length` and streamed overflow cases

Closes #548.

## Testing
- `bun test src/request-body.test.ts src/web/session-auth.test.ts`
- `bun run typecheck`

## Summary by CodeRabbit

* **Bug Fixes**
  * Login requests with oversized form bodies now return HTTP 413 with a clear error message instead of failing silently.
  * Enhanced form data parsing with explicit size limit enforcement (1 MB maximum per login request).

* **Tests**
  * Added integration tests verifying proper rejection of oversized login form submissions.

### CODE REVIEW

File: src/web/server.ts [hunk 1]
```diff
@@ -61,6 +62,7 @@ const PORT_ZERO_RETRY_ATTEMPTS = 10;
 const PORT_ZERO_FALLBACK_START = 40000;
 const PORT_ZERO_FALLBACK_SPAN = 20000;
 const MAX_PEER_AUTH_BODY_BYTES = 1024 * 1024;
+const MAX_LOGIN_FORM_BODY_BYTES = 1024 * 1024;
```
Comment (Peyton-Spencer) [inline src/web/server.ts]: Minor: The `.catch()` returning-error-as-value pattern is unconventional and makes the control flow harder to follow — `formData` can be `FormData`, `RequestBodyTooLargeError`, or `null`, requiring a type-narrowing check after.

A `try/catch` would be clearer:

```ts
let formData: FormData | null;
try {
  formData = await readFormDataBody(req, MAX_LOGIN_FORM_BODY_BYTES);
} catch (err) {
  if (err instanceof RequestBodyTooLargeError) {
    return new Response('Request body too large', { status: 413 });
  }
  formData = null;
}
```

This also matches how `readRequestBody` errors are handled elsewhere in this file (e.g. `hashRequestBodyWithLimit` on the peer-auth path).

File: src/request-body.ts [hunk 2]
```diff
@@ -68,3 +68,19 @@ export async function readJsonBody<T>(
...
 }
+
+export async function readFormDataBody(
+  req: Request,
+  maxBodyBytes: number,
+): Promise<Awaited<ReturnType<Request['formData']>>> {
+  const body = await readRequestBody(req, maxBodyBytes);
+  const contentType =
+    req.headers.get('content-type') ??
+    'application/x-www-form-urlencoded;charset=UTF-8';
```
Comment (Peyton-Spencer) [inline src/request-body.ts]: Nit: `Promise<Awaited<ReturnType<Request['formData']>>>` is just `Promise<FormData>`. The type gymnastics are harder to read for no benefit:

```ts
export async function readFormDataBody(
  req: Request,
  maxBodyBytes: number,
): Promise<FormData> {
```

File: src/request-body.ts [hunk 3]
```diff
@@ -68,3 +68,19 @@ export async function readJsonBody<T>(
...
+
+  return new Request(req.url, {
+    method: req.method,
+    headers: { 'content-type': contentType },
```
Comment (Peyton-Spencer) [inline src/request-body.ts]: Nit (design): Since the login form is always `application/x-www-form-urlencoded`, an alternative is to skip the new utility entirely and use `readRequestBody` + `new URLSearchParams(body)` inline at the call site — consistent with how `readJsonBody` is just `JSON.parse(await readRequestBody(...))`. That said, `readFormDataBody` is defensible as a reusable companion to `readJsonBody`, so this is a style preference not a blocker.

**Review by Peyton-Spencer — COMMENTED** [review]
Security fix is correct — caps the unbounded `req.formData()` at `/login` with the shared bounded reader, addressing the pre-auth memory DoS. Test coverage is solid with both content-length fast-reject and streamed overflow paths tested at unit and integration levels.

3 suggestions inline (1 minor, 2 nits). Also note this overlaps with PR #549 which addresses the same issue (#548) using a simpler `readRequestBody` + `URLSearchParams` approach — worth deciding which to land and closing the other.

**Comment by Peyton-Spencer** [comment]
Addressed the review direction in follow-up commit `067ef12`.

- Switched `/login` from the new `readFormDataBody()` helper to the simpler shared `readRequestBody()` + `URLSearchParams` path.
- Kept the oversized streamed-body regression coverage from this PR.
- Added an explicit `400 Bad request` path for non-size request read failures instead of collapsing them into invalid credentials.

This now matches the simpler shape from `#549` while keeping the stronger coverage already present here.
